llm:
  model: "gpt-4o-mini"  # or gpt-4o
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: "sk-..."  # your api key
  max_tokens: 4096  # max tokens for each request
  temperature: 1.0  # temperature for sampling

novel:
  volume_count: 1  # number of volumes to use
  chapter_count_per_volume: 3  # number of chapters per volume
  section_word_count: 2000  # word count for each section
  sliding_window_size: 5 # sliding window size for chapter outline, detailed outline and chapter generation
  workspace: "workspace"  # novel storage directory
