llm:
  model: "gpt-4o-mini"  # or gpt-4o
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: "sk-..."  # your api key
  max_tokens: 1000  # max tokens for each request
  temperature: 0.7  # temperature for sampling

novel:
  volume_count: 1  # number of volumes to use
  chapter_count_per_volume: 10  # number of chapters per volume
  section_word_count: 1000  # word count for each section
  workspace: "workspace"  # novel storage directory
